   name: CI

   on: [push, pull_request]

   jobs:
     test:
       runs-on: ubuntu-latest

       strategy:
         matrix:
           tool: [poetry, uv]

       steps:
       - uses: actions/checkout@v2

       - name: Set up Python
         uses: actions/setup-python@v2
         with:
           python-version: '3.11'

       - name: Install dependencies
         run: |
             pip install ${{ matrix.tool }}
             ${{ matrix.tool }} install

       - name: Run tests
         run: |
             ${{ matrix.tool }} run pytest
