   name: CI

   on: [push, pull_request]

   jobs:
      test-poetry:
        runs-on: ubuntu-latest

        steps:
        - uses: actions/checkout@v2

        - name: Set up Python
          uses: actions/setup-python@v2
          with:
            python-version: '3.11'

        - name: Copy pyproject
          run: |
              cp pyproject.poetry.toml pyproject.toml

        - name: Install dependencies
          run: |
              pip install poetry
              poetry install

        - name: Run tests
          run: |
              poetry run pytest
      test-uv:
        runs-on: ubuntu-latest

        steps:
        - uses: actions/checkout@v2

        - name: Set up Python
          uses: actions/setup-python@v2
          with:
            python-version: '3.11'

        - name: Copy pyproject
          run: |
              cp pyproject.uv.toml pyproject.toml

        - name: Install dependencies
          run: |
              pip install uv
              uv sync

        - name: Run tests
          run: |
              uv run python -m pytest
      test-uv-with-setup:
        runs-on: ubuntu-latest

        steps:
        - uses: actions/checkout@v2

        - name: Set up Python
          uses: actions/setup-python@v2
          with:
            python-version: '3.11'

        - name: Copy pyproject
          run: |
              cp pyproject.uv.toml pyproject.toml
          
        - name: Install the latest version of uv
          uses: astral-sh/setup-uv@v3
          with:
            version: "latest"

        - name: Install dependencies
          run: |
              uv sync

        - name: Run tests
          run: |
              uv run python -m pytest